name: Python CI/CD

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: MarkdownLint

    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: markdownlint-cli
        if: matrix.python-version == '3.8'
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "*.md docs/*.md"
          config_file: ".markdownlint.yaml"